# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 21:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('private', models.BooleanField(default=True)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('de_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Map')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='playbook',
            name='role1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role1', to='core.Role'),
        ),
        migrations.AddField(
            model_name='playbook',
            name='role2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role2', to='core.Role'),
        ),
        migrations.AddField(
            model_name='playbook',
            name='role3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role3', to='core.Role'),
        ),
        migrations.AddField(
            model_name='playbook',
            name='role4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role4', to='core.Role'),
        ),
        migrations.AddField(
            model_name='playbook',
            name='role5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role5', to='core.Role'),
        ),
    ]
